// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1l4WgWdDD4t_nvEq7XTbIZj1nfg6HytY',
    appId: '1:682808397176:web:ee3cfc02a8d498a7b3cc8d',
    messagingSenderId: '682808397176',
    projectId: 'ecommerceapp-17f9c',
    authDomain: 'ecommerceapp-17f9c.firebaseapp.com',
    storageBucket: 'ecommerceapp-17f9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxhwPIi6PozNkRZvCHO7O2OLAiRU4ZzD0',
    appId: '1:682808397176:android:f21bf7e438646bf7b3cc8d',
    messagingSenderId: '682808397176',
    projectId: 'ecommerceapp-17f9c',
    storageBucket: 'ecommerceapp-17f9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2E2mWlwuRNoGQb16ZNO0dr6uUTWfYH8U',
    appId: '1:682808397176:ios:98f18a9312e7ca6eb3cc8d',
    messagingSenderId: '682808397176',
    projectId: 'ecommerceapp-17f9c',
    storageBucket: 'ecommerceapp-17f9c.firebasestorage.app',
    androidClientId: '682808397176-o5hnb93ul2vs3ah837bsq7mp91s2ujs3.apps.googleusercontent.com',
    iosClientId: '682808397176-6dil2upatrgbmblkid363nd6nfs1c57q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystore',
  );

}